### ISSUE TITLE
Fatal error:  Uncaught Error: Function name must be a string

### ISSUE THREAD

**Issue by hinaloe** [kurudrive/VK-All-in-One-Expansion-Unit#121]
```
PHP Notice:  Array to string conversion in ....\wordpress\wp-content\plugins\vk-all-in-one-expansion-unit\admin_wrapper.php on line 62
PHP Notice:  Undefined property: vExUnit_icons::$Arr
about:blankay in ....\wordpress\wp-content\plugins\vk-all-in-one-expansion-unit\admin_wrapper.php on line 62
PHP Fatal error:  Uncaught Error: Function name must be a string in ....\wordpress\wp-content\plugins\vk-all-in-one-expansion-unit\admin_wrapper.php:62
Stack trace:
#0 ....\wordpress\wp-includes\plugin.php(525): vkExUnit_render_main_config('')
#1 ....\wordpress\wp-admin\admin.php(236): do_action('vk-ex-unit_page...')
#2 {main}
  thrown in ....\wordpress\wp-content\plugins\vk-all-in-one-expansion-unit\admin_wrapper.php on line 62
```

( on PHP7 RC4)

~~一気にプラグインバージョン飛ばしたことによる不整合?~~

```php
				$vkoption['render_page'][0]->{$vkoption['render_page'][1]}();
```

ですね。

**Comment by kurudrive** [comment]
ありがとうございました。
